[tool.poetry]
name = "type-infer"
version = "0.0.1"
description = "Automated type inference for Machine Learning pipelines."
authors = ["MindsDB Inc. <hello@mindsdb.com>"]
license = "GPL-3.0"
readme = "README.md"
packages = [{include = "type_infer"}]

[tool.poetry.dependencies]
python = "^3.9, > 3.6"
python-dateutil = "^2.8.2"
scipy = "^1.9.1"
numpy = "^1.23.3"
pandas = "^1.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
