[tool.poetry]
name = "type-infer"
version = "0.0.1"
description = "Automated type inference for Machine Learning pipelines."
authors = ["MindsDB Inc. <hello@mindsdb.com>"]
license = "GPL-3.0"
readme = "README.md"
packages = [{include = "type_infer"}]

[tool.poetry.dependencies]
python = "3.7,3.8,3.9"
python-dateutil = "^2.8.1"
scipy = "^1.9.1"
pandas = "^1.5.0"
numpy = "^1.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
